
    // Determine the single selected comparison year, otherwise use the default 'LFY' year
    VAR comp_year_selection = SELECTEDVALUE( 'Filter - Comparison Year'[Comparison Year] )
    VAR comp_year = 
        IF( 
            ISBLANK(comp_year_selection) = FALSE(),
            comp_year_selection,
            CALCULATE( 
                SELECTEDVALUE( 'Filter - Comparison Year'[Comparison Year] ), 
                'Filter - Comparison Year'[Comparison Year (with current)] = "LFY"
            )
        )

    // Calculate the diff between the largest select Year and the selected CompYear
    // Multiply to fit per-year adjustment on numbers like 202651
    VAR adjustment_base = MAX( Calendar[FinYear Number] ) - comp_year
    VAR adjustment_100 = adjustment_base * 100
    
    // Reviewing the days in each of the maximum selected weeks and its comparison year pair
    
    // Maximum is considered within the visual, ignoring any context inside the visual via ALLSELECTED()
    VAR max_yearweek = CALCULATE( MAX( 'Calendar'[FinYearCinWeek Number] ), ALLSELECTED() )
    VAR max_yearweek_max_weekday = CALCULATE( MAX( Calendar[FinCinWeekday Number] ), ALLSELECTED(), 'Calendar'[FinYearCinWeek Number] = max_yearweek )
    
    // Determine if the max_week is in context. Used for optimisation and calculation of the max week comp
    VAR selected_yearweeks = DISTINCT( Calendar[FinYearCinWeek Number] )
    VAR max_yearweek_in_context = IF( max_yearweek IN selected_yearweeks, TRUE(), FALSE() )
    VAR max_compyearweek_unadj = IF( max_yearweek_in_context = TRUE(), max_yearweek - adjustment_100, BLANK() )
    VAR max_compyearweek_unadj_yr_str = LEFT( max_compyearweek_unadj, 4 )
    // Adds offset
    VAR max_compyearweek =
        IF(
            max_yearweek_in_context = TRUE(),
            SWITCH(
                TRUE(),
                
                max_yearweek_in_context = TRUE() && max_compyearweek_unadj = 202553,
                202601,
                
                max_yearweek_in_context = TRUE() && max_compyearweek_unadj_yr_str = "2025",
                max_compyearweek_unadj + 1,
                
                max_compyearweek_unadj
                
            ),
            BLANK()
        )
        
    // Finding the total possible weekdays in each of the weeks
    VAR max_yearweek_total_weekdays = CALCULATE( MAX( Calendar[FinCinWeekday Number] ), ALL(), 'Calendar'[FinYearCinWeek Number] = max_yearweek )
    VAR max_compyearweek_total_weekdays = 
        IF(
            max_yearweek_in_context = TRUE(),  // Only calculated when needed
            CALCULATE( MAX( Calendar[FinCinWeekday Number] ), ALL(), 'Calendar'[FinYearCinWeek Number] = max_compyearweek ),
            BLANK()
        )
        
    // Gather similiar data on the max month to handle fallback logic for full month selections
    VAR max_yearmonth = 
        IF( 
            max_yearweek_in_context = TRUE(), 
            CALCULATE( MAX( 'Calendar'[FinYearCinMonth Number] ), ALLSELECTED() ), 
            BLANK()
        )
    
    VAR min_yearmonth_max_monthday = 
        IF( 
            max_yearweek_in_context = TRUE(), 
            CALCULATE( MIN( Calendar[FinCinMonthDay Number] ), ALLSELECTED(), 'Calendar'[FinYearCinMonth Number] = max_yearmonth ), 
            BLANK()
    )
    
    VAR max_yearmonth_day_count = 
        IF( 
            max_yearweek_in_context = TRUE() && min_yearmonth_max_monthday = 1,
            CALCULATE( DISTINCTCOUNTNOBLANK( 'Calendar'[Date] ), ALLSELECTED(), 'Calendar'[FinYearCinMonth Number] = max_yearmonth ), 
            BLANK()
        )
        
    VAR max_compyearmonth = 
        IF( 
            max_yearweek_in_context = TRUE() && min_yearmonth_max_monthday = 1,
            max_yearmonth - adjustment_100, 
            BLANK()
        )
    
    VAR max_compyearmonth_max_monthday = 
        IF( 
            max_yearweek_in_context = TRUE() && min_yearmonth_max_monthday = 1, 
            CALCULATE( MAX( Calendar[FinCinMonthDay Number] ), ALL(), 'Calendar'[FinYearCinMonth Number] = max_compyearmonth ), 
            BLANK()
        )
    
    // Determine the maximum weekday number used to filter the maximum comparison week
    VAR max_compyearweek_max_compweekday = 
        IF(
            max_yearweek_in_context = TRUE(),  // Only calculated when needed
            IF(
                // IF Only some of the days are selected 
                ( max_yearweek_max_weekday < max_yearweek_total_weekdays ) &&
                // AND the max month is selected from its first day, and its total count of days is NOT >= to days in the comparison month
                NOT( min_yearmonth_max_monthday = 1 && max_yearmonth_day_count >= max_compyearmonth_max_monthday ), 
                // THEN use the max selected weekday
                max_yearweek_max_weekday,
                
                // ELSE select all weekdays via a high number. This specific number works as an indicator as well
                99
            ),
            BLANK()
        )
        
    // Create the list of Comp-Year-Week-Weekdays to be selected, excluding the maximum
    // Always selects all days in the comparison weeks, and operates relative to the selection
    // Adds offset
    VAR cond_offset = IF( max_compyearweek_unadj_yr_str = "2025", 1, 0 )
    VAR non_max_compfinyearcinweeks_unalt =
        CALCULATETABLE(
            // Distinct column of Year-Week-Weekdays adjusted back to the comparison
            SELECTCOLUMNS(
                DISTINCT( Calendar[FinYearCinWeek Number] ),
                "comp", 'Calendar'[FinYearCinWeek Number] - adjustment_100 + cond_offset
            ),
            // Maintain any row filters using the calendar
            KEEPFILTERS( 'Calendar' ),
            // All days in weeks that are not the max selected year week
            'Calendar'[FinYearCinWeek Number] <> max_yearweek
        )
        
    // If week 1 was selected, add it back into the adjusted weeks
    VAR selected_fincin_weeks = DISTINCT( Calendar[FinCinWeek Number] )
    VAR non_max_compfinyearcinweeks = 
        UNION(
            non_max_compfinyearcinweeks_unalt,
            ROW(
                "FinYearCinWeek Number",
                IF(
                    cond_offset = 1 && 1 IN selected_fincin_weeks,
                    202501,
                    - 1
                )
            )
        )
        
    // Find the applicable Comp-Year-Week-Weekdays within the max comparison week
    // All context is ignored, this is a pure lookup
    VAR max_compfinyearcinweek_weekdays = 
        CALCULATETABLE(
            // Distinct column of Year-Week-Weekdays
            DISTINCT( Calendar[FINYEARCINWEEKWEEKDAY_NUMBER] ),
            // Drop all context - this is a pure lookup
            ALL(),
            // Get all valid Year-Week-Weekdays in the max comp week...
            // IF relevant to the weeks in context
            max_yearweek_in_context = TRUE() &&
            (
                // INCLUDE the max compyearweek
                'Calendar'[FinYearCinWeek Number] = max_compyearweek ||
                // ALSO INCLUDE the (possible) 53rd week, but only when 99 shows we are selecting all weekdays
                ( 
                    MOD ( max_compyearweek, 100 ) = 52 &&  // Checks last 2 digits of the number
                    max_compyearweek_max_compweekday = 99 &&  // Is in the select-all state
                    'Calendar'[FinYearCinWeek Number] = max_compyearweek + 1
                )
            ) &&
            // WITHIN those weeks, only the allowed days.
            // This will be all days in both weeks except when less than the full weekdays are selected in the max week
            'Calendar'[FinCinWeekday Number] <= max_compyearweek_max_compweekday
        )
                
RETURN
    CALCULATE(
        // Calculate selected measure
        SELECTEDMEASURE(),
        // Drop all calendar context except those that should still influence what is calculated
        ALLEXCEPT(
            'Calendar',
            Calendar[IS_FUTURE_DATE],
            Calendar[FUTURE_DATES_FILTER],
            Calendar[RECENT_DATES_FILTER],
            Calendar[Date is in EMPLive],
            Calendar[Date is in Film Hire],
            Calendar[Date is in Aggregate],
            Calendar[Date is in any table]
        ),
        // Calculate the measure for parts in either of the 2 selection methods
        'Calendar'[FinYearCinWeek Number] IN non_max_compfinyearcinweeks ||
        'Calendar'[FINYEARCINWEEKWEEKDAY_NUMBER] IN max_compfinyearcinweek_weekdays 
    )