SELECT * FROM EDW_TRB_PRD.SEMANTIC.VW_THREDBO_EMPLIVE_PAYROLL_DAILY_PBI;
-- 1,741,648

CREATE TEMP TABLE EDW_TRB_PRD.SEMANTIC.TRB_TEMP_DAILY AS SELECT * FROM EDW_TRB_PRD.SEMANTIC.VW_THREDBO_EMPLIVE_PAYROLL_DAILY_PBI;

SELECT * FROM EDW_TRB_PRD.SEMANTIC.TRB_TEMP_DAILY;

SELECT
    "Start Date"
    ,COUNT(*) AS row_count
FROM EDW_TRB_PRD.SEMANTIC.TRB_TEMP_DAILY
GROUP BY "Start Date"
ORDER BY "Start Date";
